config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'homes/about' => 'homes#about', as: 'about'

  resources :postimages, only: [:new, :create, :index, :show, :destroy] do
    resources :postcomments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :postimage
end

app/models/postcomment.rb
class Postcomment < ApplicationRecord
  belongs_to :user
  belongs_to :postimage
end

app/models/postimage.rb
class Postimage < ApplicationRecord
  belongs_to :user
  has_many :postcomments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :image

  validates :shop_name, presence: true
  validates :image, presence: true

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :postimages, dependent: :destroy
  has_many :postcomments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :profile_image

  def get_profile_image(height, width)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [height, width]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top]


  def after_sign_in_path_for(resource)
    postimages_path
  end
  def after_sign_out_path_for(resource)
    about_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    postimage = Postimage.find(params[:postimage_id])
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.postimage_id = postimage.id
    favorite.save

    redirect_to postimage_path(favorite.postimage_id)
  end

  def destroy
    postimage = Postimage.find(params[:postimage_id])
    favorite = current_user.favorites.find_by(postimage_id: postimage.id)
    favorite.destroy
    redirect_to postimage_path(favorite.postimage_id)
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/postcomments_controller.rb
class PostcommentsController < ApplicationController
  def create
    postimage = Postimage.find(params[:postimage_id])
    comment = Postcomment.new(postcomment_params)
    comment.user_id = current_user.id
    comment.postimage_id = postimage.id
    comment.save
    redirect_to postimage_path(postimage.id)
  end

  def destroy
    postcomment = Postcomment.find(params[:id])
    postcomment.destroy
    redirect_to postimage_path(postcomment.postimage_id)
  end

  private

  def postcomment_params
    params.require(:postcomment).permit(:comment)
  end
end

app/controllers/postimages_controller.rb
class PostimagesController < ApplicationController
  def new
    @postimage = Postimage.new
  end

  def create
    @postimage = Postimage.new(postimage_params)
    @postimage.user_id = current_user.id
    if @postimage.save
      redirect_to postimage_path(@postimage.id)
    else
      render :new
    end
  end

  def index
    @postimages = Postimage.all
  end

  def show
    @postimage = Postimage.find(params[:id])
    @postcomment = Postcomment.new
  end

  def destroy
    @postimage = Postimage.find(params[:id])
    @postimage.destroy
    redirect_to postimages_path
  end

  private

  def postimage_params
    params.require(:postimage).permit(:shop_name, :caption, :image, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(current_user.id)
  end

  def show
    @user = User.find(params[:id])
    @postimages = @user.postimages
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/postcomments_helper.rb
module PostcommentsHelper
end

app/helpers/postimages_helper.rb
module PostimagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<h1>ここはABOUTページです</h1>

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meshitero2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
        <ul>
          <li>
            <%= link_to "投稿フォーム", new_postimage_path %>
          </li>
          <li>
            <%= link_to "マイページ", user_path(current_user.id) %>
          </li>
          <li>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          </li>
        </ul>
      <% else %>
       <ul>
          <li>
            <%= link_to "ログイン", new_user_session_path %>
          </li>
          <li>
            <%= link_to "新規登録", new_user_registration_path %>
          </li>
        </ul>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/postimages/index.html.erb
<h1>投稿一覧</h1>


<% @postimages.each do |postimage| %>

  <div>
    <h4>投稿ユーザー画像</h4>
    <%= image_tag postimage.user.get_profile_image(100,100) %><br>

    <%= link_to postimage_path(postimage.id) do %>
      <%= image_tag postimage.get_image %>
    <% end %>

    <h4>ショップ名</h4>
    <%= postimage.shop_name %>

    <h4>説明</h4>
    <%= postimage.caption %>

    <p>コメント件数: <%= postimage.postcomments.count %></p>
  </div>

<% end %>

app/views/postimages/new.html.erb
<h1>新規投稿</h1>

<% if @postimage.errors.any? %>
  <p><%= @postimage.errors.count %>件のエラーが発生しています</p>
  <% @postimage.errors.full_messages.each do |message| %>
  <ul>
    <li><%= message %></li>
  </ul>
  <% end %>
<% end %>

<%= form_with model:@postimage do |f| %>
  <h4><%= f.label "画像" %></h4>
  <%= f.file_field :image, accept: 'images/*' %>

  <h4><%= f.label "ショップ名" %></h4>
  <%= f.text_field :shop_name %>

  <h4><%= f.label "説明" %></h4>
  <%= f.text_area :caption %>

  <%= f.submit "投稿" %>

<% end %>

app/views/postimages/show.html.erb
<div>
  <%= image_tag @postimage.get_image %>
  <p>ショップ名: <%= @postimage.shop_name %></p>
  <p>説明: <%= @postimage.caption %></p>
  <p>投稿ユーザー画像: <%= image_tag @postimage.user.get_profile_image(100,100)  %></p>
  <p>ユーザーネーム: <%= @postimage.user.name %></p>
  <p>投稿日: <%= @postimage.created_at.strftime('%Y/%m/%d') %></p>
  <% if @postimage.user == current_user %>
    <%= link_to "削除", postimage_path(@postimage.id), method: :delete %>
  <% end %>
  <% if @postimage.favorited_by?(current_user) %>
      <p>
        <%= link_to postimage_favorites_path(@postimage.id), method: :delete do %>
          ❤︎ <%= @postimage.favorites.count %> いいね
        <% end %>
      </p>
    <% else %>
      <p>
        <%= link_to postimage_favorites_path(@postimage.id), method: :post do %>
          ♡︎ <%= @postimage.favorites.count %> いいね
        <% end %>
      </p>
    <% end %>
</div>

<div>
  <p>コメント件数: <%= @postimage.postcomments.count %></p>
  <% @postimage.postcomments.each do |postcomment| %>

    <p><%= image_tag @postimage.user.get_profile_image(100,100) %></p>
    <%= postcomment.user.name %>
    <%= postcomment.created_at.strftime('%Y/%m/%d') %><%= postcomment.comment %>
    <% if postcomment.user == current_user %>
      <%= link_to "削除", postimage_postcomment_path(postcomment.postimage.id, postcomment.id), method: :delete %>
    <% end %>


    <% end %>
</div>

<div>
  <%= form_with model:[@postimage, @postcomment], method: :post do |f| %>
    <%= f.text_area :comment, rows:'5', placeholder: 'コメントをここに' %>
    <%= f.submit "送信する" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>

<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <label for="inputImage">ProfileImage</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>  
  <%= f.submit "変更を保存" %>
<% end %>

app/views/users/show.html.erb
<div>
  <h3><%= @user.name %></h3>
  <%= image_tag @user.get_profile_image(100,100) %>
  <% if @user == current_user %>
    <p><%= link_to "プロフィール編集", edit_user_path(@user.id) %></p>
  <% end %>
</div>

<% @postimages.each do |postimage| %>
  <div>
    <%= link_to postimage_path(postimage.id) do %>
      <%= image_tag postimage.get_image %>
    <% end %>
    <p>投稿ユーザー画像: <%= image_tag 'sample-author1.jpg'  %></p>
    <p>ショップ名: <%= postimage.shop_name %></p>
    <p>説明: <%= postimage.caption %></p>
    <p>ユーザーネーム: <%= postimage.user.name %></p>
    <p>コメント件数: <%= postimage.postcomments.count %></p>
  </div>
<% end %>